site_name: Soumya Shreeram
site_description: Astrophysics | Research software developer
site_author: Soumya Shreeram
site_url: https://soumya_shreeram.github.io

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
  font:
    text: Roboto
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy

nav:
  - Home: index.md
  - Research: research.md
  - Publications: publications.md
  - Lightcone Project: lightcone.md
  - Data & Software: data.md
  - Contact: contact.md

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
